name: AutoBuild

on:
  push:
    branches: ["main", "add_actions"]
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "*.md"
      - "**.txt"
      - "LICENSE"
  pull_request:
    branches: ["main", "add_actions"]
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "**/*.md"
      - "README.md"
      - "LICENSE"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      actions: write

    env:
      QT_DIR: ${{ github.workspace }}/Qt

    steps:
      - uses: actions/checkout@v4

      - name: Cache Qt
        uses: actions/cache@v4
        with:
          path: ${{ env.QT_DIR }}
          key: ${{ runner.os }}-qt-${{ hashFiles('**/CMakeLists.txt') }}-qt690
          restore-keys: |
            ${{ runner.os }}-qt-

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.9.0"
          arch: "win64_msvc2022_64"
          dir: ${{ env.QT_DIR }}
          setup-python: true
          tools: "tools_cmake tools_ninja tools_opensslv3_x64 tools_vcredist"

      - name: Configure Build
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" ^
                -DCMAKE_BUILD_TYPE=Release ^
                -DCMAKE_PREFIX_PATH="${{ env.QT_DIR }}/6.9.0/msvc2022_64" ^
                -DBUILD_SHARED_LIBS=OFF ^
                ..
      - name: Build app for release
        run: |
          cd build
          msbuild ../ScreenCapture.sln ^
                  -t:rebuild ^
                  -p:Configuration=Release ^
                  -p:Platform=x64 ^
                  -verbosity:normal

      - name: Verify Qt DLLs
        run: |
          dumpbin /dependents ./build/Release/ScreenCapture.exe

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Preview
          path: ./build/Release/ScreenCapture.exe